In [7]:
import torch
import numpy as np

In [14]:
np_data = np.arange(6).reshape((2,3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(np_data,'\n', torch_data,'\n', tensor2array)

[[0 1 2]
 [3 4 5]] 
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
 [[0 1 2]
 [3 4 5]]


In [15]:
data = [-1,-2,1,2]
tensor = torch.FloatTensor(data)
print(np.abs(data))
print(torch.abs(tensor))

[1 2 1 2]
tensor([1., 2., 1., 2.])


In [18]:
tensor.abs()

tensor([1., 2., 1., 2.])

In [21]:
print(np.sin(data))

[-0.84147098 -0.90929743  0.84147098  0.90929743]


In [22]:
print(tensor.sin())

tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [24]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [25]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

In [28]:
print(np.mean(data))
print(tensor.mean())

0.0
tensor(0.)


In [32]:
data = np.array(data)
data

array([-1, -2,  1,  2])

In [ ]:
tensor = torch.Tensor([1,2,3,4])
print(data.dot(data))
print(torch.dot(tensor.do))